### ISSUE TITLE
The app crashed after wake up

### ISSUE THREAD

**Issue by qwfpg** [OnionBrowser/OnionBrowser#325]
iOS 14.5.1. Trying to wake up application crashed it. Settings of tab security setup on remember tab. Similar issues described [here](https://github.com/OnionBrowser/OnionBrowser/issues/311)  but on beta iOS version

**Comment by qwfpg** [comment]
@tladesignz I glad to help if you shortly will describe me a reason of the bug

**Comment by tladesignz** [comment]
Sorry, but this is way too little information.

You might have experienced that it sometimes does *not* crash when coming back? So, while it might crash sometimes (or even often) when *you* use it, that's not the case with standard usage. Otherwise we would have noticed and fixed, already.

So, there must be certain circumstances. Typically bridges? If you're using Snowflake bridges, then that wouldn't surprise me. We're working on improving that, but that's a hard nut to crack, because that's third-party code and a lot of stuff outside the realms of Onion Browser. (E.g.: there must be a snowflake available for you!)

Or it's something else which is triggered by some specific configuration and/or list of pages you have loaded.

**Comment by qwfpg** [comment]
@tladesignz so, I try to use it with default configuration without third party bridges. Just check remember tabs in tab security

**Comment by tladesignz** [comment]
Ok, I played around more and finally understood, when the problem happens.

Steps to reproduce:

1. Should work with current master build.
2. Start Onion Browser fresh (direct connection, no bridges)
3. Send in background by either switching off the device or via home button/swipe.
4. Switch back on/get it back into foreground, while iOS *didn't* shut it down completely, yet.
5. After Tor is restarted and the blurred image should go away, app will instead crash, **but only if not debugging**!

That's going to be tricky. It's **not** happening while connected to the debugger. Not sure how to debug this.

**Comment by tladesignz** [comment]
Ok, got this:

The watchdog timer kills the app:

https://developer.apple.com/documentation/xcode/addressing-watchdog-terminations

Reason: `#applicationDidEnterBackground` is still processing when app is returning to foreground.

Underlying problem: HSTS cache file is too big. > 10 MB, takes over 10 seconds to write. Moving in background thread remedies the crash, but cache file still takes too long to write. `HSTSCache` needs to be improved.

Fix will be contained in next release!
